# Generated by Django 4.2.17 on 2024-12-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SrtrAsistencia',
            fields=[
                ('n_id_asistencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('t_hora_inicio', models.DateTimeField(null=True)),
                ('t_hora_fin', models.DateTimeField(null=True)),
                ('c_estado', models.CharField(db_comment='Asistencia del personal (0:No asisti¾, 1:Asisti¾, 2:Tardanza).', max_length=1, null=True)),
                ('d_fecha', models.DateField(null=True)),
            ],
            options={
                'db_table': 'srtr_asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrtrImagen',
            fields=[
                ('n_id_imagen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cl_imagen_biometrica', models.ImageField(upload_to='personas/')),
                ('cl_encoding', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'srtr_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrthDependencia',
            fields=[
                ('n_id_dependencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_descripcion', models.CharField(max_length=255, null=True)),
                ('v_abreviatura', models.CharField(max_length=70, null=True)),
            ],
            options={
                'db_table': 'SRTH_DEPENDENCIA',
            },
        ),
        migrations.CreateModel(
            name='SrtrPersonal',
            fields=[
                ('n_id_personal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v_cod_personal', models.CharField(max_length=7)),
                ('v_nombre', models.CharField(max_length=70, null=True)),
                ('v_apellido_paterno', models.CharField(max_length=70, null=True)),
                ('v_apellido_materno', models.CharField(max_length=70, null=True)),
                ('v_correo_institucional', models.CharField(max_length=80, null=True)),
                ('n_telefono_contacto', models.BigIntegerField(null=True)),
                ('n_num_doc', models.BigIntegerField(null=True)),
                ('v_disponibilidad', models.CharField(db_comment='Disponibilidad del personal seg·n la fecha', max_length=20, null=True)),
                ('c_estado', models.CharField(max_length=1, null=True)),
                ('n_id_dependencia', models.ForeignKey(db_column='n_id_dependencia', on_delete=django.db.models.deletion.CASCADE, to='reconocimientoFacial.srthdependencia')),
            ],
            options={
                'db_table': 'SRTR_PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='SrtrRepositorioImagen',
            fields=[
                ('n_id_rep_imagen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_id_personal', models.ForeignKey(db_column='n_id_personal', on_delete=django.db.models.deletion.CASCADE, to='reconocimientoFacial.srtrpersonal')),
            ],
            options={
                'db_table': 'SRTR_REPOSITORIO_IMAGEN',
            },
        ),
    ]
